apiVersion: v1
kind: Service
metadata:
  name: castor-garage-api
  namespace: castor-garage
  labels:
    app: castor-garage-api
spec:
  selector:
    app: castor-garage-api
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
