apiVersion: v1
kind: ConfigMap
metadata:
  name: castor-garage-config
  namespace: castor-garage
data:
  PORT: "3000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: "8h"
  ADMIN_EMAIL: "admin@oficina.com"
  POSTGRES_DB: "mecanica_db"
  POSTGRES_USER: "workshop"
