apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mecanica
type: Opaque
data:
  # echo -n 'workshop' | base64
  POSTGRES_USER: d29ya3Nob3A=
  # echo -n 'workshop' | base64
  POSTGRES_PASSWORD: d29ya3Nob3A=
  # echo -n 'mecanica_db' | base64
  POSTGRES_DB: bWVjYW5pY2FfZGI=
